⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/_generated_/common/.config/taskfiles/install/Taskfile-python.yml b/_generated_/common/.config/taskfiles/install/Taskfile-python.yml
--- a/_generated_/common/.config/taskfiles/install/Taskfile-python.yml
+++ b/_generated_/common/.config/taskfiles/install/Taskfile-python.yml
@@ -82,7 +82,12 @@ tasks:
           poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
         else
           .config/log info 'Installing Poetry dependencies{{if .INSTALL_OPTIONS}} with options `{{.INSTALL_OPTIONS}}`{{end}}'
-          poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
+          poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}} || EXIT_CODE=$?
+          if [ -n "$EXIT_CODE" ]; then
+            .config/log warn 'Running `poetry install{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}` failed.'
+            .config/log info 'Attempting to fix by running `poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}`'
+            poetry update{{if .INSTALL_OPTIONS}} {{.INSTALL_OPTIONS}}{{end}}
+          fi
         fi
     sources:
       - pyproject.toml
