automation(upstream-sync) Applying changes from upstream repository.

diff --git a/taskfiles-role/Taskfile-common.yml b/taskfiles-role/Taskfile-common.yml
--- a/taskfiles-role/Taskfile-common.yml
+++ b/taskfiles-role/Taskfile-common.yml
@@ -1,5 +1,5 @@
 ---
-version: "3"
+version: '3'
 
 tasks:
   autopopulate-ansible-dependencies:
@@ -166,22 +166,22 @@ tasks:
       then install the Python requirements by running `pip3 install -r requirements` after
       initiating a `virtualenv`. In some types of projects, additional types of requirements are
       installed (e.g. Ansible projects also install Ansible Galaxy requirements).
-    deps: [nodejs-dependencies, nodejs-global-dependencies, python-requirements, galaxy-requirements]
+    deps: [nodejs-dependencies, nodejs-global-dependencies, python-requirements]
 
   galaxy-requirements:
     deps: [python-requirements]
     cmds:
       - |
         if [ "${container:=}" != 'docker' ]; then
-          bash .common/log log "Running \`ansible-galaxy install -r requirements.yml --ignore-errors\`"
+          bash .common/log log "Running \"ansible-galaxy install -r requirements.yml --ignore-errors\""
           ansible-galaxy install -r requirements.yml --ignore-errors
           bash .common/log success "Successfully installed Ansible Galaxy requirements"
         fi
     sources:
       - requirements.yml
     preconditions:
-      - sh: "test -f requirements.yml"
-        msg: "The requirements.yml file is missing! It should be present even if it is empty (which should almost never be the case)."
+      - sh: 'test -f requirements.yml'
+        msg: 'The requirements.yml file is missing! It should be present even if it is empty (which should almost never be the case).'
 
   reset:
     desc: Resets the project by removing all caches and updating the project
@@ -200,7 +200,7 @@ tasks:
   reset-force:
     deps:
       - software:git
-    desc: "Aggressively reset the project (WARNING: This will wipe uncommitted work)"
+    desc: 'Aggressively reset the project (WARNING: This will wipe uncommitted work)'
     summary: |
       $ Aggressively reset the project
 
@@ -220,10 +220,10 @@ tasks:
     cmds:
       - |
         if [ "${container:=}" != 'docker' ]; then
-          bash .common/log info "Running \`npm install\`"
+          bash .common/log info "Running \"npm install\""
           npm install
-          npm audit fix --force
-          bash .common/log success "Successfully ran \`npm install\`"
+          npm audit fix --force || true
+          bash .common/log success "Successfully ran \"npm install\""
         fi
     sources:
       - package.json
@@ -231,8 +231,8 @@ tasks:
     status:
       - test -d node_modules
     preconditions:
-      - sh: "test -f package.json"
-        msg: "The package.json file appears to be missing!"
+      - sh: 'test -f package.json'
+        msg: 'The package.json file appears to be missing!'
 
   nodejs-global-dependencies:
     deps: [npm-hbs, npm-prettier, npm-prettier-package-json, npm-readme, npm-snyk]
@@ -245,7 +245,7 @@ tasks:
     cmds:
       - |
         if [ "${container:=}" != 'docker' ]; then
-          bash .common/log info "Running \`npm install -g {{.NPM_PACKAGE}}\`"
+          bash .common/log info "Running \"npm install -g {{.NPM_PACKAGE}}\""
           npm install -g {{.NPM_PACKAGE}}
           bash .common/log success "`The npm {{.NPM_PACKAGE}}` package is globally installed"
         fi
@@ -277,7 +277,7 @@ tasks:
     cmds:
       - task: npm-install
         vars:
-          NPM_PACKAGE: "@appnest/readme"
+          NPM_PACKAGE: '@appnest/readme'
           NPM_PACKAGE_BIN: readme
 
   npm-snyk:
@@ -294,6 +294,7 @@ tasks:
       - task: python-requirements-venv
       - task: python-requirements-venv-activate
       - task: python-requirements-pip
+      - task: galaxy-requirements
     status:
       - '[[ "${container:=}" == "docker" ]]'
 
@@ -318,7 +319,7 @@ tasks:
       - . .venv/bin/activate
     preconditions:
       - sh: test -f .venv/bin/activate
-        msg: "`.venv/bin/activate` is missing!"
+        msg: '`.venv/bin/activate` is missing!'
 
   python-requirements-pip:
     cmds:
@@ -326,8 +327,8 @@ tasks:
     sources:
       - requirements.txt
     preconditions:
-      - sh: "test -f requirements.txt"
-        msg: "The requirements.txt file is missing!"
+      - sh: 'test -f requirements.txt'
+        msg: 'The requirements.txt file is missing!'
 
   python-virtualenv:
     cmds:
@@ -365,8 +366,8 @@ tasks:
         fi
       - task: shell-prompt
     preconditions:
-      - sh: "type docker &> /dev/null"
-        msg: "Docker is not installed! Install it by running `task software:docker`."
+      - sh: 'type docker &> /dev/null'
+        msg: 'Docker is not installed! Install it by running `task software:docker`.'
 
     shell-prompt:
       deps:
@@ -380,8 +381,8 @@ tasks:
             docker run --cap-drop=ALL -it -v "$PWD:/{{.WORKDIR}}" -w /{{.WORKDIR}} --rm "megabytelabs/ansible-molecule-${OS_CHOICE}:latest" /bin/bash
           fi
       preconditions:
-        - sh: "type node &> /dev/null"
-          msg: "Node.js is not installed! Install it by running `task software:node`."
+        - sh: 'type node &> /dev/null'
+          msg: 'Node.js is not installed! Install it by running `task software:node`.'
       status:
         - '[[ ! -z "{{.CLI_ARGS}}" ]]'
 
@@ -407,8 +408,8 @@ tasks:
     cmds:
       - npx cspell --no-summary --no-progress --show-context --no-must-find-files --config .common/.cspell.json "$STAGED_FILES" || true
     preconditions:
-      - sh: "git diff --cached --name-only"
-        msg: "Cannot perform a spell check because there are no staged files"
+      - sh: 'git diff --cached --name-only'
+        msg: 'Cannot perform a spell check because there are no staged files'
 
   update:
     deps: [update-ansible-galaxy-id, autopopulate-ansible-dependencies, update-repositories]
@@ -421,7 +422,7 @@ tasks:
 
   update-repositories:
     cmds:
-      # - task: update-common
+      - task: update-common
       - task: update-modules
       - task: update-project
 
@@ -437,8 +438,8 @@ tasks:
       - git pull origin master --ff-only || true
       - cd ..
     preconditions:
-      - sh: "type git &> /dev/null"
-        msg: "git is not installed! You can install it by running `task software:git`."
+      - sh: 'type git &> /dev/null'
+        msg: 'git is not installed! You can install it by running `task software:git`.'
 
   update-finish:
     deps: []
@@ -468,19 +469,19 @@ tasks:
       TMP:
         sh: mktemp
     vars:
-      COMMON_JSON: ".common/common.{{.REPOSITORY_SUBTYPE}}.json"
+      COMMON_JSON: '.common/common.{{.REPOSITORY_SUBTYPE}}.json'
     cmds:
       - jq -S --arg blueprint "$BLUEPRINT_DATA" '. = . * ($blueprint | fromjson)' ".common/variables.{{.REPOSITORY_SUBTYPE}}.json" > "$TMP"
       - mv "$TMP" .variables.json
       - task: update-variables-role
     sources:
-      - ".common/variables.{{.REPOSITORY_SUBTYPE}}.json"
+      - '.common/variables.{{.REPOSITORY_SUBTYPE}}.json'
       - package.json
     preconditions:
-      - sh: "type jq &> /dev/null"
-        msg: "jq is not installed! You can install it by running `task software:jq`."
-      - sh: "type yq &> /dev/null"
-        msg: "yq is not installed! You can install it by running `task software:yq`."
+      - sh: 'type jq &> /dev/null'
+        msg: 'jq is not installed! You can install it by running `task software:jq`.'
+      - sh: 'type yq &> /dev/null'
+        msg: 'yq is not installed! You can install it by running `task software:yq`.'
 
   update-variables-role:
     deps:
@@ -506,17 +507,17 @@ tasks:
         '.subheader_description = $subheader | .alternative_description = $alt | .galaxy_info = ($galaxyinfo | fromjson)' .variables.json > "$TMP"
       - mv "$TMP" .variables.json
     preconditions:
-      - sh: "type jq &> /dev/null"
-        msg: "jq is not installed! You can install it by running `task software:jq`."
-      - sh: "type yq &> /dev/null"
-        msg: "yq is not installed! You can install it by running `task software:yq`."
-      - sh: "test -f meta/main.yml"
-        msg: "The `meta/main.yml` file is missing. A properly populated `meta/main.yml` is required. You can find an
-          example of one at https://github.com/ProfessorManhattan/ansible-snapd."
+      - sh: 'type jq &> /dev/null'
+        msg: 'jq is not installed! You can install it by running `task software:jq`.'
+      - sh: 'type yq &> /dev/null'
+        msg: 'yq is not installed! You can install it by running `task software:yq`.'
+      - sh: 'test -f meta/main.yml'
+        msg: 'The `meta/main.yml` file is missing. A properly populated `meta/main.yml` is required. You can find an
+          example of one at https://github.com/ProfessorManhattan/ansible-snapd.'
       - sh: test -f .variables.json
-        msg: "The `.variables.json` file is missing!"
+        msg: 'The `.variables.json` file is missing!'
     sources:
-      - ".common/variables.{{.REPOSITORY_SUBTYPE}}.json"
+      - '.common/variables.{{.REPOSITORY_SUBTYPE}}.json'
       - meta/main.yml
       - package.json
 
@@ -547,7 +548,7 @@ tasks:
           done
         fi
     status:
-      - "! ls .modules/*/ > /dev/null 2>&1"
+      - '! ls .modules/*/ > /dev/null 2>&1'
 
   update-readme-role:
     deps: [mod-ansible-autodoc]
@@ -568,12 +569,13 @@ tasks:
       - mkdir -p .autodoc
       - mv ansible_actions.md ansible_tags.md ansible_todo.md ansible_variables.json ansible_variables.md ansible_variables_header.md .autodoc
     sources:
-      - "tasks**/*.yml"
-      - ".autodoc/*"
+      - 'tasks**/*.yml'
+      - '.autodoc/*'
     preconditions:
-      - sh: "type mod-ansible-autodoc &> /dev/null"
-        msg: "The Python package `mod-ansible-autodoc` is missing. Ensure all the requirements are installed by running `task common:requirements`.
-          Also, ensure `mod-ansible-autodoc` is included in the `requirements.txt` file."
+      - sh: 'type mod-ansible-autodoc &> /dev/null'
+        msg:
+          'The Python package `mod-ansible-autodoc` is missing. Ensure all the requirements are installed by running `task common:requirements`.
+          Also, ensure `mod-ansible-autodoc` is included in the `requirements.txt` file.'
 
   _mod-ansible-autodoc:
     env:
@@ -602,8 +604,8 @@ tasks:
       - task: ansibler-compatibility-chart
       - task: _ansibler
     preconditions:
-      - sh: "type ansibler &> /dev/null"
-        msg: "`ansibler` is not installed globally. Install all the requirements by running `task common:requirements`."
+      - sh: 'type ansibler &> /dev/null'
+        msg: '`ansibler` is not installed globally. Install all the requirements by running `task common:requirements`.'
     status:
       - true
 
@@ -644,12 +646,12 @@ tasks:
     sources:
       - .variables.json
     preconditions:
-      - sh: "test -f .common/docs/blueprint-contributing.md"
-        msg: "The CONTRIBUTING.md template file is not present at `.common/docs/blueprint-contributing.md`"
-      - sh: "test -f .variables.json"
-        msg: "The .variables.json file is not present. Generate it by running `task common:update`."
+      - sh: 'test -f .common/docs/blueprint-contributing.md'
+        msg: 'The CONTRIBUTING.md template file is not present at `.common/docs/blueprint-contributing.md`'
+      - sh: 'test -f .variables.json'
+        msg: 'The .variables.json file is not present. Generate it by running `task common:update`.'
       - sh: type readme &> /dev/null
-        msg: "`@appnest/readme` is not installed globally. Install all the requirements by running `task common:requirements`."
+        msg: '`@appnest/readme` is not installed globally. Install all the requirements by running `task common:requirements`.'
 
   update-files:
     deps:
@@ -690,10 +692,10 @@ tasks:
       - package.json
       - .variables.json
     preconditions:
-      - sh: "type rsync &> /dev/null"
-        msg: "`rsync` is not installed!"
-      - sh: "type prettier-package-json &> /dev/null"
-        msg: "`prettier-package-json` is not installed globally. Install all the requirements by running `task common:requirements`."
+      - sh: 'type rsync &> /dev/null'
+        msg: '`rsync` is not installed!'
+      - sh: 'type prettier-package-json &> /dev/null'
+        msg: '`prettier-package-json` is not installed globally. Install all the requirements by running `task common:requirements`.'
 
   update-ansible-galaxy-id:
     vars:
@@ -727,8 +729,8 @@ tasks:
     sources:
       - .variables.json
     preconditions:
-      - sh: "type hbs &> /dev/null"
-        msg: "`hbs-cli` is not installed globally. Install all the requirements by running `task common:requirements`."
+      - sh: 'type hbs &> /dev/null'
+        msg: '`hbs-cli` is not installed globally. Install all the requirements by running `task common:requirements`.'
 
   update-latestos:
     deps:
@@ -746,7 +748,7 @@ tasks:
       - '[[ "{{.TAG}}}" == "macos" ]] || [ "${container:=}" == "docker" ]'
     preconditions:
       - sh: test -f template.json
-        msg: "The `template.json` file is missing from the root of this project."
+        msg: 'The `template.json` file is missing from the root of this project.'
 
   update-readme:
     deps: [npm-prettier, npm-readme]
@@ -764,14 +766,14 @@ tasks:
       - .autodoc/*
       - .variables.json
     preconditions:
-      - sh: "test -f .common/docs/{{.README_TEMPLATE}}"
-        msg: "The README.md template file is not present at `.common/docs/{{.README_TEMPLATE}}`."
-      - sh: "test -f .variables.json"
-        msg: "The `.variables.json` file is not present. Generate it by running `task common:update`."
+      - sh: 'test -f .common/docs/{{.README_TEMPLATE}}'
+        msg: 'The README.md template file is not present at `.common/docs/{{.README_TEMPLATE}}`.'
+      - sh: 'test -f .variables.json'
+        msg: 'The `.variables.json` file is not present. Generate it by running `task common:update`.'
       - sh: type readme &> /dev/null
-        msg: "`@appnest/readme` is not installed globally. Install all the requirements by running `task common:requirements`."
+        msg: '`@appnest/readme` is not installed globally. Install all the requirements by running `task common:requirements`.'
       - sh: type prettier &> /dev/null
-        msg: "`prettier` is not installed globally. Install all the requirements by running `task common:requirements`."
+        msg: '`prettier` is not installed globally. Install all the requirements by running `task common:requirements`.'
 
   update-readme-packer:
     cmds:
@@ -812,7 +814,8 @@ tasks:
 
   _markdown-scrub:
     vars:
-      DIVIDER_SRC: <a href="\1" style="width:100%"><img style="width:100%" alt="-----------------------------------------------------"
+      DIVIDER_SRC:
+        <a href="\1" style="width:100%"><img style="width:100%" alt="-----------------------------------------------------"
         src="https://gitlab.com/megabyte-labs/assets/-/raw/master/png/aqua-divider.png" /></a>
       REGEX: .*https://raw.githubusercontent.com/andreasbm/readme/master/assets/lines/.*.png)][(]\(.*\)[)].*$
     cmds:
