⤵️ automation(synchronize) Applying changes from upstream repository.

diff --git a/.config/taskfiles/install/Taskfile-python.yml b/.config/taskfiles/install/Taskfile-python.yml
--- a/.config/taskfiles/install/Taskfile-python.yml
+++ b/.config/taskfiles/install/Taskfile-python.yml
@@ -56,14 +56,14 @@ tasks:
     deps:
       - :install:software:poetry
     run: once
-    cmds:
-      - poetry config virtualenvs.create {{.PYTHON_VIRTUALENV}}
-      - poetry config virtualenvs.in-project true
-      - poetry install
     log:
       error: Failed to configure / install via `poetry`
       start: Configuring Poetry and running `poetry install`
       success: Successfully ran `poetry install`
+    cmds:
+      - poetry config virtualenvs.create {{.PYTHON_VIRTUALENV}}
+      - poetry config virtualenvs.in-project true
+      - poetry install
     sources:
       - pyproject.toml
     preconditions:
@@ -93,21 +93,21 @@ tasks:
   venv:node:
     deps:
       - :install:software:python
-    cmds:
-      - |
-        REQUIREMENTS_PATH="$PWD/requirements.txt"
-        cd "$INIT_CWD" || exit
-        if [ ! -d .venv ]; then
-          python3 -m venv .env
-        else
-          .config/log warn 'The `.venv` folder is already present so a fresh virtualenv cannot be installed'
-        fi
-        . .venv/bin/activate
-        pip3 install -U pip setuptools
-        pip3 install -r "$REQUIREMENTS_PATH"
     log:
       error: Encountered error while setting up `.venv` environment
       start: Setting up a Python 3 `.venv`
       success: Finished setting up `.venv`. Run `. .venv/bin/activate` to load the environment into your shell.
+    cmds:
+      - |
+        REQUIREMENTS_PATH="$PWD/.config/requirements.txt"
+        cd "$INIT_CWD" || exit
+        if [ ! -f .venv/bin/activate ]; then
+          python3 -m venv .env
+        else
+          .config/log warn 'The `.venv` folder is already present so a fresh virtualenv cannot be installed (there is a small chance of a conflict)'
+        fi
+        . .venv/bin/activate
+        pip3 install -U pip setuptools
+        pip3 install -r "$REQUIREMENTS_PATH"
     sources:
       - requirements.txt
