☁️ chore(automation): Applying changes from upstream repository.

diff --git a/_generated_/common/.config/taskfiles/ansible/Taskfile-test.yml b/_generated_/common/.config/taskfiles/ansible/Taskfile-test.yml
--- a/_generated_/common/.config/taskfiles/ansible/Taskfile-test.yml
+++ b/_generated_/common/.config/taskfiles/ansible/Taskfile-test.yml
@@ -218,6 +218,15 @@ tasks:
       **Save test results for use with auto-generating compatibility chart:**
       `task ansible:test:molecule:docker:matrix`
     cmds:
+      - |
+        if ! docker run --rm hello-world; then
+        .config/log warn 'The command `docker run --rm hello-world` failed'
+          if [ -f '/Applications/Docker.app' ]; then
+            .config/log info 'Attempting to open `Applications/Docker.app` (Docker Desktop for macOS)'
+            open /Applications/Docker.app
+            sleep 30
+          fi
+        fi
       - task: molecule:docker:{{if .CLI_ARGS}}cli{{else}}prompt{{end}}
 
   molecule:docker:cli:
